[2024-06-26T04:20:10.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:20:10.177+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:20:10.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:20:10.181+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:20:10.188+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:20:10.209+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:20:10.210+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmporvkd90a']
[2024-06-26T04:20:10.213+0000] {standard_task_runner.py:63} INFO - Started process 56 to run task
[2024-06-26T04:20:10.213+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask load_market_data
[2024-06-26T04:20:10.277+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:20:10.644+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:20:10.646+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:20:10.809+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:20:11.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:20:11.066+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 74, in load_market_data
    flattened_dataframe.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-06-26T04:20:11.113+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T042010, end_date=20240626T042011
[2024-06-26T04:20:11.290+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task load_market_data ((psycopg2.errors.UndefinedColumn) column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 56)
[2024-06-26T04:20:11.325+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:20:11.353+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:20:11.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T04:22:49.793+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:22:49.809+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:22:49.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:22:49.814+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:22:49.820+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:22:49.823+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:22:49.824+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-06-26T04:22:49.824+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpa9s3xxzq']
[2024-06-26T04:22:49.825+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask load_market_data
[2024-06-26T04:22:49.862+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:22:49.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:22:49.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:22:49.996+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:22:50.018+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:22:50.019+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 74, in load_market_data
    flattened_dataframe.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-06-26T04:22:50.034+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T042249, end_date=20240626T042250
[2024-06-26T04:22:50.043+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task load_market_data ((psycopg2.errors.UndefinedColumn) column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 63)
[2024-06-26T04:22:50.092+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:22:50.107+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:22:50.109+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T04:25:48.881+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:25:48.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:25:48.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:25:48.901+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:25:48.907+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:25:48.910+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:25:48.910+0000] {standard_task_runner.py:63} INFO - Started process 56 to run task
[2024-06-26T04:25:48.911+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpvonuw7mx']
[2024-06-26T04:25:48.912+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask load_market_data
[2024-06-26T04:25:48.947+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:25:49.064+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:25:49.064+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:25:49.074+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:25:49.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:25:49.098+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 74, in load_market_data
    flattened_dataframe.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-06-26T04:25:49.114+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T042548, end_date=20240626T042549
[2024-06-26T04:25:49.124+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task load_market_data ((psycopg2.errors.UndefinedColumn) column "volume_weighted" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                         ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 56)
[2024-06-26T04:25:49.133+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:25:49.147+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:25:49.148+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T04:31:10.020+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:31:10.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:31:10.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:31:10.042+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:31:10.049+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:31:10.052+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:31:10.053+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-06-26T04:31:10.053+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpjztfi2y4']
[2024-06-26T04:31:10.055+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask load_market_data
[2024-06-26T04:31:10.098+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:31:10.262+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:31:10.263+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:31:10.272+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:31:10.293+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:31:10.294+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 74, in load_market_data
    flattened_dataframe.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                                          ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-06-26T04:31:10.321+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T043110, end_date=20240626T043110
[2024-06-26T04:31:10.329+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task load_market_data ((psycopg2.errors.UndefinedColumn) column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                                          ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 63)
[2024-06-26T04:31:10.355+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:31:10.370+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:31:10.371+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T04:33:54.409+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:33:54.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:33:54.428+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:33:54.429+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:33:54.435+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:33:54.437+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:33:54.438+0000] {standard_task_runner.py:63} INFO - Started process 56 to run task
[2024-06-26T04:33:54.438+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp1_ytu6nj']
[2024-06-26T04:33:54.439+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask load_market_data
[2024-06-26T04:33:54.475+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:33:54.587+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:33:54.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:33:54.598+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:33:54.618+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:33:54.619+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, vw, opening_price, closing_...
                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 74, in load_market_data
    flattened_dataframe.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, vw, opening_price, closing_...
                                             ^

[SQL: INSERT INTO market_data (volume, vw, opening_price, closing_price, high_price, low_price, timestamp, n, symbol) VALUES (%(volume)s, %(vw)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(n)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'vw': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'n': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'vw': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'n': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'vw': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'n': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'vw': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'n': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'vw': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'n': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'vw': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'n': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'vw': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'n': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'vw': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'n': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'vw': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'n': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'vw': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'n': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-06-26T04:33:54.632+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T043354, end_date=20240626T043354
[2024-06-26T04:33:54.640+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task load_market_data ((psycopg2.errors.UndefinedColumn) column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, vw, opening_price, closing_...
                                             ^

[SQL: INSERT INTO market_data (volume, vw, opening_price, closing_price, high_price, low_price, timestamp, n, symbol) VALUES (%(volume)s, %(vw)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(n)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'vw': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'n': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'vw': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'n': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'vw': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'n': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'vw': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'n': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'vw': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'n': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'vw': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'n': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'vw': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'n': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'vw': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'n': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'vw': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'n': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'vw': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'n': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 56)
[2024-06-26T04:33:54.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:33:54.672+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:33:54.673+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T04:43:18.676+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:43:18.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:43:18.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:43:18.700+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:43:18.708+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:43:18.710+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:43:18.711+0000] {standard_task_runner.py:63} INFO - Started process 98 to run task
[2024-06-26T04:43:18.712+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmprhjrlx19']
[2024-06-26T04:43:18.713+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask load_market_data
[2024-06-26T04:43:18.749+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:43:18.859+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:43:18.860+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:43:18.875+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:43:18.899+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:43:18.899+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 75, in load_market_data
    flattened_dataframe.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                                          ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-06-26T04:43:18.913+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T044318, end_date=20240626T044318
[2024-06-26T04:43:18.920+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 92 for task load_market_data ((psycopg2.errors.UndefinedColumn) column "opening_price" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data (volume, volume_weighted, opening_pr...
                                                          ^

[SQL: INSERT INTO market_data (volume, volume_weighted, opening_price, closing_price, high_price, low_price, timestamp, number_of_transactions, symbol) VALUES (%(volume)s, %(volume_weighted)s, %(opening_price)s, %(closing_price)s, %(high_price)s, %(low_price)s, %(timestamp)s, %(number_of_transactions)s, %(symbol)s)]
[parameters: ({'volume': 47314924.0, 'volume_weighted': 149.8529, 'opening_price': 151.54, 'closing_price': 149.93, 'high_price': 152.38, 'low_price': 148.39, 'timestamp': datetime.datetime(2024, 1, 2, 5, 0), 'number_of_transactions': 476432, 'symbol': 'AMZN'}, {'volume': 49410095.0, 'volume_weighted': 149.4055, 'opening_price': 149.2, 'closing_price': 148.47, 'high_price': 151.05, 'low_price': 148.33, 'timestamp': datetime.datetime(2024, 1, 3, 5, 0), 'number_of_transactions': 416954, 'symbol': 'AMZN'}, {'volume': 56039807.0, 'volume_weighted': 145.416, 'opening_price': 145.59, 'closing_price': 144.57, 'high_price': 147.38, 'low_price': 144.05, 'timestamp': datetime.datetime(2024, 1, 4, 5, 0), 'number_of_transactions': 541342, 'symbol': 'AMZN'}, {'volume': 45003147.0, 'volume_weighted': 145.4485, 'opening_price': 144.69, 'closing_price': 145.24, 'high_price': 146.59, 'low_price': 144.53, 'timestamp': datetime.datetime(2024, 1, 5, 5, 0), 'number_of_transactions': 380385, 'symbol': 'AMZN'}, {'volume': 46757053.0, 'volume_weighted': 148.3238, 'opening_price': 146.74, 'closing_price': 149.1, 'high_price': 149.4, 'low_price': 146.15, 'timestamp': datetime.datetime(2024, 1, 8, 5, 0), 'number_of_transactions': 410733, 'symbol': 'AMZN'}, {'volume': 43812567.0, 'volume_weighted': 150.6311, 'opening_price': 148.33, 'closing_price': 151.37, 'high_price': 151.71, 'low_price': 148.21, 'timestamp': datetime.datetime(2024, 1, 9, 5, 0), 'number_of_transactions': 403026, 'symbol': 'AMZN'}, {'volume': 44421830.0, 'volume_weighted': 153.4523, 'opening_price': 152.06, 'closing_price': 153.73, 'high_price': 154.42, 'low_price': 151.881, 'timestamp': datetime.datetime(2024, 1, 10, 5, 0), 'number_of_transactions': 430517, 'symbol': 'AMZN'}, {'volume': 49072691.0, 'volume_weighted': 155.0181, 'opening_price': 155.04, 'closing_price': 155.18, 'high_price': 157.17, 'low_price': 153.12, 'timestamp': datetime.datetime(2024, 1, 11, 5, 0), 'number_of_transactions': 468131, 'symbol': 'AMZN'}  ... displaying 10 of 120 total bound parameter sets ...  {'volume': 66858255.0, 'volume_weighted': 188.0574, 'opening_price': 187.8, 'closing_price': 189.08, 'high_price': 189.275, 'low_price': 185.86, 'timestamp': datetime.datetime(2024, 6, 21, 4, 0), 'number_of_transactions': 435715, 'symbol': 'AMZN'}, {'volume': 48143614.0, 'volume_weighted': 187.3312, 'opening_price': 189.33, 'closing_price': 185.57, 'high_price': 191.0, 'low_price': 185.33, 'timestamp': datetime.datetime(2024, 6, 24, 4, 0), 'number_of_transactions': 535288, 'symbol': 'AMZN'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 98)
[2024-06-26T04:43:18.933+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:43:18.945+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:43:18.946+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T04:48:27.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:48:27.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:48:27.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T04:48:27.867+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T04:48:27.874+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T04:48:27.877+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:48:27.878+0000] {standard_task_runner.py:63} INFO - Started process 56 to run task
[2024-06-26T04:48:27.878+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpziy11v0b']
[2024-06-26T04:48:27.879+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask load_market_data
[2024-06-26T04:48:27.920+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T04:48:28.056+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T04:48:28.057+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:48:28.067+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T04:48:28.091+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-26T04:48:28.092+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:48:28.104+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T044827, end_date=20240626T044828
[2024-06-26T04:48:28.139+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T04:48:28.155+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:48:28.156+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T05:14:12.206+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T05:14:12.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T05:14:12.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T05:14:12.231+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T05:14:12.238+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T05:14:12.241+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T05:14:12.241+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2024-06-26T05:14:12.242+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpokoqous0']
[2024-06-26T05:14:12.243+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask load_market_data
[2024-06-26T05:14:12.279+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T05:14:12.427+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T05:14:12.427+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T05:14:12.436+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T05:14:12.451+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-26T05:14:12.452+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T05:14:12.472+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T051412, end_date=20240626T051412
[2024-06-26T05:14:12.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T05:14:12.523+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T05:14:12.525+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T08:45:11.702+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T08:45:11.716+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T08:45:11.722+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T08:45:11.722+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T08:45:11.730+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T08:45:11.741+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T08:45:11.742+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-06-26T08:45:11.743+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp8yywb4g7']
[2024-06-26T08:45:11.745+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask load_market_data
[2024-06-26T08:45:11.855+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T08:45:12.046+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T08:45:12.049+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T08:45:12.069+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T08:45:12.120+0000] {python.py:237} INFO - Done. Returned value was:        volume  volume_weighted  ...  number_of_transactions  symbol
0  44586537.0           186.97  ...                  382026    AMZN

[1 rows x 9 columns]
[2024-06-26T08:45:12.132+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T08:45:12.169+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T084511, end_date=20240626T084512
[2024-06-26T08:45:12.221+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T08:45:12.246+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-26T08:45:12.248+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T08:58:10.127+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T08:58:10.144+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T08:58:10.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T08:58:10.150+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T08:58:10.158+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-26T08:58:10.165+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T08:58:10.166+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2024-06-26T08:58:10.167+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpypjmbi3y']
[2024-06-26T08:58:10.168+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask load_market_data
[2024-06-26T08:58:10.225+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-26T08:58:10.394+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T08:58:10.395+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T08:58:10.404+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-26T08:58:10.428+0000] {python.py:237} INFO - Done. Returned value was:        volume  volume_weighted  ...  number_of_transactions  symbol
0  44586537.0           186.97  ...                  382026    AMZN

[1 rows x 9 columns]
[2024-06-26T08:58:10.434+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T08:58:10.478+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T085810, end_date=20240626T085810
[2024-06-26T08:58:10.514+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T08:58:10.539+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-26T08:58:10.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T02:41:40.070+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T02:41:40.084+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T02:41:40.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T02:41:40.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-27T02:41:40.096+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-27T02:41:40.101+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T02:41:40.102+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2024-06-27T02:41:40.103+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpkk5zevk7']
[2024-06-27T02:41:40.104+0000] {standard_task_runner.py:91} INFO - Job 192: Subtask load_market_data
[2024-06-27T02:41:40.171+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-27T02:41:40.332+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-27T02:41:40.333+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T02:41:40.343+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-27T02:41:40.364+0000] {python.py:237} INFO - Done. Returned value was:     Symbol  ...  Close_Date
0     ADBL  ...  2024-06-24
1  ADBLD83  ...  2024-06-24
2      AHL  ...  2024-06-24
3     AHPC  ...  2024-06-24
4    AKJCL  ...  2024-06-24

[5 rows x 15 columns]
[2024-06-27T02:41:40.376+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T02:41:40.422+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240627T024140, end_date=20240627T024140
[2024-06-27T02:41:40.449+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T02:41:40.470+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-27T02:41:40.471+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T02:52:22.719+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T02:52:22.746+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T02:52:22.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T02:52:22.753+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-27T02:52:22.760+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-27T02:52:22.767+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T02:52:22.768+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-06-27T02:52:22.769+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpi061l3lr']
[2024-06-27T02:52:22.770+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask load_market_data
[2024-06-27T02:52:22.843+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-27T02:52:23.032+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-27T02:52:23.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T02:52:23.045+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-27T02:52:23.079+0000] {python.py:237} INFO - Done. Returned value was:     Symbol  ...  Close_Date
0     ADBL  ...  2024-06-24
1  ADBLD83  ...  2024-06-24
2      AHL  ...  2024-06-24
3     AHPC  ...  2024-06-24
4    AKJCL  ...  2024-06-24

[5 rows x 15 columns]
[2024-06-27T02:52:23.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T02:52:23.115+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240627T025222, end_date=20240627T025223
[2024-06-27T02:52:23.157+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T02:52:23.183+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-27T02:52:23.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T02:59:14.648+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T02:59:14.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T02:59:14.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T02:59:14.670+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-27T02:59:14.679+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-27T02:59:14.682+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T02:59:14.683+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-06-27T02:59:14.684+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpmixgzics']
[2024-06-27T02:59:14.685+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask load_market_data
[2024-06-27T02:59:14.722+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-27T02:59:14.862+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-27T02:59:14.863+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T02:59:14.871+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-27T02:59:14.889+0000] {python.py:237} INFO - Done. Returned value was:     Symbol  ...  Close_Date
0     ADBL  ...  2024-06-24
1  ADBLD83  ...  2024-06-24
2      AHL  ...  2024-06-24
3     AHPC  ...  2024-06-24
4    AKJCL  ...  2024-06-24

[5 rows x 15 columns]
[2024-06-27T02:59:14.899+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T02:59:14.924+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240627T025914, end_date=20240627T025914
[2024-06-27T02:59:14.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T02:59:14.970+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-27T02:59:14.971+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T03:09:09.640+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T03:09:09.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T03:09:09.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T03:09:09.664+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-27T03:09:09.671+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-06-27T03:09:09.676+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T03:09:09.677+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2024-06-27T03:09:09.677+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp36aeun4f']
[2024-06-27T03:09:09.678+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask load_market_data
[2024-06-27T03:09:09.732+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-27T03:09:09.917+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-27T03:09:09.918+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T03:09:09.927+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-27T03:09:10.003+0000] {python.py:237} INFO - Done. Returned value was:   Symbol  Close_Price_Rs  ...  Market_Capitalization_Rs__Amt_in_Millions  Close_Date
0   ADBL           263.0  ...                                   35377.90  2024-06-26
1    AHL           513.1  ...                                    1744.54  2024-06-26
2   AHPC           152.0  ...                                    5678.61  2024-06-26
3  AKJCL           207.0  ...                                    1656.00  2024-06-26
4   AKPL           161.1  ...                                    6276.36  2024-06-26

[5 rows x 15 columns]
[2024-06-27T03:09:10.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T03:09:10.050+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240627T030909, end_date=20240627T030910
[2024-06-27T03:09:10.068+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T03:09:10.087+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-27T03:09:10.088+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-01T02:40:43.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T02:40:43.175+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-01T02:40:43.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-01T02:40:43.181+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-01T02:40:43.188+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-07-01T02:40:43.192+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-01T02:40:43.192+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-07-01T02:40:43.193+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpvqqtlo_k']
[2024-07-01T02:40:43.194+0000] {standard_task_runner.py:91} INFO - Job 293: Subtask load_market_data
[2024-07-01T02:40:43.229+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host 5eec0a067191
[2024-07-01T02:40:43.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-07-01T02:40:43.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T02:40:43.408+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-07-01T02:40:43.427+0000] {python.py:237} INFO - Done. Returned value was:     Symbol  ...  Close_Date
0     ADBL  ...  2024-03-05
1  ADBLD83  ...  2024-03-05
2      AHL  ...  2024-03-05
3     AHPC  ...  2024-03-05
4    AKJCL  ...  2024-03-05

[5 rows x 15 columns]
[2024-07-01T02:40:43.436+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T02:40:43.459+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240701T024043, end_date=20240701T024043
[2024-07-01T02:40:43.502+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-01T02:40:43.518+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-01T02:40:43.519+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-01T04:58:37.978+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T04:58:37.992+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-01T04:58:37.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-01T04:58:37.997+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-01T04:58:38.004+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-07-01T04:58:38.017+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-01T04:58:38.017+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-07-01T04:58:38.018+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpw3p75hfp']
[2024-07-01T04:58:38.019+0000] {standard_task_runner.py:91} INFO - Job 319: Subtask load_market_data
[2024-07-01T04:58:38.058+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host 5eec0a067191
[2024-07-01T04:58:38.231+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-07-01T04:58:38.232+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T04:58:38.242+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-07-01T04:58:38.261+0000] {python.py:237} INFO - Done. Returned value was:   Symbol  Close_Price_Rs  ...  Market_Capitalization_Rs__Amt_in_Millions  Close_Date
0   ADBL           239.0  ...                                   32149.50  2024-05-05
1    AHL           441.0  ...                                    1499.40  2024-05-05
2   AHPC           162.0  ...                                    6052.20  2024-05-05
3  AKJCL           208.0  ...                                    1664.00  2024-05-05
4   AKPL           165.6  ...                                    6451.68  2024-05-05

[5 rows x 15 columns]
[2024-07-01T04:58:38.275+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T04:58:38.302+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240701T045837, end_date=20240701T045838
[2024-07-01T04:58:38.367+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-01T04:58:38.386+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-01T04:58:38.387+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-06T12:20:55.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-06T12:20:55.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-06T12:20:55.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-06T12:20:55.575+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-06T12:20:55.580+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-07-06T12:20:55.583+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-06T12:20:55.584+0000] {standard_task_runner.py:63} INFO - Started process 78 to run task
[2024-07-06T12:20:55.584+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmphq43a_2s']
[2024-07-06T12:20:55.586+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_market_data
[2024-07-06T12:20:55.612+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host 97487d04705a
[2024-07-06T12:20:55.710+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-07-06T12:20:55.711+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-06T12:20:55.716+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-06T12:20:55.719+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 66, in load_market_data
    market_database_conn = market_database_hook.get_sqlalchemy_engine()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 239, in get_sqlalchemy_engine
    return create_engine(self.get_uri(), **engine_kwargs)
                         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 204, in get_uri
    return self.sqlalchemy_url.render_as_string(hide_password=False)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 119, in sqlalchemy_url
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `market_database_conn` isn't defined
[2024-07-06T12:20:55.727+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240706T122055, end_date=20240706T122055
[2024-07-06T12:20:55.737+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task load_market_data (The conn_id `market_database_conn` isn't defined; 78)
[2024-07-06T12:20:55.765+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-06T12:20:55.777+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-06T12:20:55.778+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-06T12:32:18.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-06T12:32:18.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-06T12:32:18.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-06T12:32:18.584+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-06T12:32:18.589+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-07-06T12:32:18.592+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-06T12:32:18.593+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-07-06T12:32:18.593+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp8p9y0mlm']
[2024-07-06T12:32:18.594+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_market_data
[2024-07-06T12:32:18.614+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host 0b441d8ce42a
[2024-07-06T12:32:18.702+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-07-06T12:32:18.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-06T12:32:18.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-06T12:32:18.711+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 66, in load_market_data
    market_database_conn = market_database_hook.get_sqlalchemy_engine()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 239, in get_sqlalchemy_engine
    return create_engine(self.get_uri(), **engine_kwargs)
                         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 204, in get_uri
    return self.sqlalchemy_url.render_as_string(hide_password=False)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 119, in sqlalchemy_url
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `market_database_conn` isn't defined
[2024-07-06T12:32:18.717+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240706T123218, end_date=20240706T123218
[2024-07-06T12:32:18.722+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task load_market_data (The conn_id `market_database_conn` isn't defined; 64)
[2024-07-06T12:32:18.735+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-06T12:32:18.743+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-06T12:32:18.744+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-06T12:41:11.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-06T12:41:11.391+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-06T12:41:11.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-06T12:41:11.395+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-06T12:41:11.400+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-25 00:00:00+00:00
[2024-07-06T12:41:11.404+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-06T12:41:11.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpmu533hoq']
[2024-07-06T12:41:11.407+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-07-06T12:41:11.407+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_market_data
[2024-07-06T12:41:11.428+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host 03e268ada1a3
[2024-07-06T12:41:11.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-07-06T12:41:11.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-06T12:41:11.549+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-06T12:41:11.553+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 66, in load_market_data
    market_database_conn = market_database_hook.get_sqlalchemy_engine()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 239, in get_sqlalchemy_engine
    return create_engine(self.get_uri(), **engine_kwargs)
                         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 204, in get_uri
    return self.sqlalchemy_url.render_as_string(hide_password=False)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 119, in sqlalchemy_url
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `market_database_conn` isn't defined
[2024-07-06T12:41:11.559+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240706T124111, end_date=20240706T124111
[2024-07-06T12:41:11.565+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task load_market_data (The conn_id `market_database_conn` isn't defined; 71)
[2024-07-06T12:41:11.590+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-06T12:41:11.600+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-06T12:41:11.600+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
