[2024-06-25T09:32:59.792+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T09:32:59.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-25T09:32:59.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-25T09:32:59.828+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-25T09:32:59.840+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-24 00:00:00+00:00
[2024-06-25T09:32:59.845+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T09:32:59.846+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-06-25T09:32:59.846+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpbca76t2f']
[2024-06-25T09:32:59.848+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_market_data
[2024-06-25T09:32:59.888+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-24T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-25T09:33:00.087+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-06-25T09:33:00.088+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T09:33:00.099+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T09:33:00.109+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 60, in load_market_data
    market_database_conn = market_database_hook.get_sqlalchemy_engine()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 239, in get_sqlalchemy_engine
    return create_engine(self.get_uri(), **engine_kwargs)
                         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 204, in get_uri
    return self.sqlalchemy_url.render_as_string(hide_password=False)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 119, in sqlalchemy_url
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `market_database_conn` isn't defined
[2024-06-25T09:33:00.120+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20240625T093259, end_date=20240625T093300
[2024-06-25T09:33:00.130+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task load_market_data (The conn_id `market_database_conn` isn't defined; 71)
[2024-06-25T09:33:00.152+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T09:33:00.169+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T09:33:00.170+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-25T09:38:48.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T09:38:48.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-25T09:38:48.509+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_market_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-25T09:38:48.510+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-25T09:38:48.517+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_market_data> on 2024-06-24 00:00:00+00:00
[2024-06-25T09:38:48.525+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T09:38:48.526+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-06-25T09:38:48.527+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_market_data', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp4kyb82e6']
[2024-06-25T09:38:48.528+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask load_market_data
[2024-06-25T09:38:48.581+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_market_data scheduled__2024-06-24T00:00:00+00:00 [running]> on host f3f48f0457b9
[2024-06-25T09:38:48.796+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-06-25T09:38:48.798+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T09:38:48.808+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-06-25T09:38:48.838+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T09:38:48.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T09:38:48.849+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_market_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20240625T093848, end_date=20240625T093848
[2024-06-25T09:38:48.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T09:38:48.889+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T09:38:48.890+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
