[2024-07-10T09:36:22.808+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: market_etl.create_date_dimension scheduled__2024-06-27T06:15:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
