[2024-07-15T05:05:55.509+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T05:05:55.510+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T05:05:55.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [queued]>
[2024-07-15T05:05:55.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [queued]>
[2024-07-15T05:05:55.549+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-15T05:05:55.575+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): hit_polygon_api> on 2024-07-11 06:15:00+00:00
[2024-07-15T05:05:55.586+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-07-15T05:05:55.591+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-07-15T05:05:55.595+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
[2024-07-15T05:05:55.598+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T05:05:55.601+0000] {standard_task_runner.py:63} INFO - Started process 69 to run task
[2024-07-15T05:05:55.601+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'hit_polygon_api', 'scheduled__2024-07-11T06:15:00+00:00', '--job-id', '1307', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpxq_hwept']
[2024-07-15T05:05:55.604+0000] {standard_task_runner.py:91} INFO - Job 1307: Subtask hit_polygon_api
[2024-07-15T05:05:55.694+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [running]> on host aa283b53dd54
[2024-07-15T05:05:56.272+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='hit_polygon_api' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T06:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T06:15:00+00:00'
[2024-07-15T05:05:56.275+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T05:05:57.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T05:05:57.036+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 31, in hit_polygon_api
    response_data = response.json()
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-15T05:05:57.074+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=hit_polygon_api, run_id=scheduled__2024-07-11T06:15:00+00:00, execution_date=20240711T061500, start_date=20240715T050555, end_date=20240715T050557
[2024-07-15T05:05:57.163+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1307 for task hit_polygon_api (Expecting value: line 1 column 1 (char 0); 69)
[2024-07-15T05:05:57.213+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T05:05:57.266+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T05:05:57.268+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
