[2024-07-15T05:16:03.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T05:16:03.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [queued]>
[2024-07-15T05:16:04.000+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [queued]>
[2024-07-15T05:16:04.001+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-07-15T05:16:04.011+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): hit_polygon_api> on 2024-07-11 06:15:00+00:00
[2024-07-15T05:16:04.019+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=206) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T05:16:04.020+0000] {standard_task_runner.py:63} INFO - Started process 208 to run task
[2024-07-15T05:16:04.021+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'hit_polygon_api', 'scheduled__2024-07-11T06:15:00+00:00', '--job-id', '1310', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmptlb7qj71']
[2024-07-15T05:16:04.023+0000] {standard_task_runner.py:91} INFO - Job 1310: Subtask hit_polygon_api
[2024-07-15T05:16:04.095+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.hit_polygon_api scheduled__2024-07-11T06:15:00+00:00 [running]> on host aa283b53dd54
[2024-07-15T05:16:04.177+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='hit_polygon_api' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T06:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T06:15:00+00:00'
[2024-07-15T05:16:04.178+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T05:16:05.067+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T05:16:05.069+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 31, in hit_polygon_api
    response_data = response.json()
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-15T05:16:05.113+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=hit_polygon_api, run_id=scheduled__2024-07-11T06:15:00+00:00, execution_date=20240711T061500, start_date=20240715T051603, end_date=20240715T051605
[2024-07-15T05:16:05.133+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1310 for task hit_polygon_api (Expecting value: line 1 column 1 (char 0); 208)
[2024-07-15T05:16:05.175+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T05:16:05.206+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T05:16:05.208+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
