[2024-06-26T09:30:54.957+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T09:30:54.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.flatten_market_data manual__2024-06-26T09:30:32.478075+00:00 [queued]>
[2024-06-26T09:30:54.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.flatten_market_data manual__2024-06-26T09:30:32.478075+00:00 [queued]>
[2024-06-26T09:30:54.977+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T09:30:54.985+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): flatten_market_data> on 2024-06-26 09:30:32.478075+00:00
[2024-06-26T09:30:54.993+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T09:30:54.995+0000] {standard_task_runner.py:63} INFO - Started process 60 to run task
[2024-06-26T09:30:54.996+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'flatten_market_data', 'manual__2024-06-26T09:30:32.478075+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpi9jvl8_x']
[2024-06-26T09:30:54.998+0000] {standard_task_runner.py:91} INFO - Job 156: Subtask flatten_market_data
[2024-06-26T09:30:55.039+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.flatten_market_data manual__2024-06-26T09:30:32.478075+00:00 [running]> on host f3f48f0457b9
[2024-06-26T09:30:55.145+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='flatten_market_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T09:30:32.478075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T09:30:32.478075+00:00'
[2024-06-26T09:30:55.146+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T09:30:55.146+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T09:30:55.147+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 39, in flatten_market_data
    raise ValueError("No results found in the Polygon response")
ValueError: No results found in the Polygon response
[2024-06-26T09:30:55.159+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=flatten_market_data, run_id=manual__2024-06-26T09:30:32.478075+00:00, execution_date=20240626T093032, start_date=20240626T093054, end_date=20240626T093055
[2024-06-26T09:30:55.171+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 156 for task flatten_market_data (No results found in the Polygon response; 60)
[2024-06-26T09:30:55.176+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T09:30:55.195+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T09:30:55.196+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
